#!/bin/zsh

if sound_info=$(osascript -e 'get volume settings') ; then
  if [[ "$(echo $sound_info | awk '{print $8}')" = "muted:false" ]]; then
    # AppleScript から取得される出力例:
    # output volume:50, input volume:75, alert volume:100, output muted:false
    volume=$(echo "$sound_info" | awk -F'[,: ]+' '{print $3}')  # output volume 値 (0〜100)

    # 全体を 16 セルに正規化
    max_cells=16
    sound_volume=$(( volume * max_cells / 100 ))

    str=""
    for ((i=0; i<sound_volume; i++)); do
      str+="■"
    done
    for ((i=sound_volume; i<max_cells; i++)); do
      str+=" "
    done
    sound="#[bold][${str}]#[default] "
  else
    sound="#[bold][   mute   ]#[default] "
  fi
  echo "$sound"
fi
