#!/bin/bash

#/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | egrep "(\ SSID)" | awk '{print $2" " $3" " $4" " $5" " $6 ;}'

is_mac()   { [[ $(echo $OSTYPE | tr '[A-Z]' '[a-z]') =~ 'darwin' ]]; }
is_linux() { [[ $(echo $OSTYPE | tr '[A-Z]' '[a-z]') =~ 'linux' ]]; }

function get_ssid()
{
    local ssid=
    if is_mac; then
        airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'
        if [ -f "$airport" ]; then
            ssid=$("$airport" -I | egrep "(\ SSID)" | awk '{print $2}')
        fi
    elif is_linux; then
        ssid=$(iwgetid -r 2>/dev/null) || \
        ssid=$(nmcli -t -f active,ssid dev wifi 2>/dev/null | grep '^yes' | cut -d: -f2)
    fi

    if [ -z "$ssid" ]; then
        ssid='no_wifi'
        echo "$ssid"
        return 1
    fi
    echo "$ssid"
}

get_ssid
